#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"

# if not running in terminal (no tty), try to spawn one
if [ ! -t 1 ]; then
    for term in ptyxis gnome-terminal konsole xfce4-terminal x-terminal-emulator xterm; do
        if command -v "$term" >/dev/null 2>&1; then
            exec "$term" -e "$HERE/usr/bin/linuxtoys" "$@"
            exit 0
        fi
    done
    echo "No terminal emulator found!"
    exit 1
fi

# if already in terminal
exec "$HERE/usr/bin/linuxtoys" "$@"
