#!/bin/bash
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export PATH="$APPDIR/usr/bin:$PATH"
# Set SSL certificate path
export SSL_CERT_FILE="$APPDIR/etc/ssl/certs/ca-certificates.crt"
export SSL_CERT_DIR="$APPDIR/etc/ssl/certs"
export CURL_CA_BUNDLE="$APPDIR/etc/ssl/certs/ca-certificates.crt"
# set git path
export GIT_EXEC_PATH="$APPDIR/usr/lib/git-core"

# if not running in terminal (no tty), try to spawn one
if [ ! -t 1 ]; then
    for term in ptyxis gnome-terminal konsole xfce4-terminal x-terminal-emulator xterm; do
        if command -v "$term" >/dev/null 2>&1; then
            exec "$term" -e "$APPDIR/usr/bin/linuxtoys" "$@"
            exit 0
        fi
    done
    echo "No terminal emulator found!"
    exit 1
fi

# if already in terminal
exec "$APPDIR/usr/bin/linuxtoys" "$@"
